[default]
# locale = "en-gb"
extend-ignore-re = [
  # Custom ignore regex patterns: https://github.com/crate-ci/typos/blob/master/docs/reference.md#example-configurations
  "(?s)//\\s*spellchecker:ignore-next-line[^\\n]*\\n[^\\n]*",
]

[default.extend-words]
# Don't correct regex part in src/extractor.ts#77
communit = "communit"

[files]
extend-exclude = ["test/unit/__snapshots__/*", "test/unit/fixtures/*"]
